apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 670420294708.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          ports:
          - containerPort: 3000
          env:
          - name: POSTGRES_HOST_URL
            value: "http://a2bfb876c0748486f8bb12e4ad5e4166-754180400.us-east-1.elb.amazonaws.com"
